language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t fgiopp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fgiopp/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "docker-travis-aws"
  env: "DockerTravisAws-env"
  bucket_name: "elasticbeanstalk-eu-south-1-759315199516"
  bucket_path: "docker-travis-aws"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"